
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mehedi Hasan
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPaymentID = new javax.swing.JTextField();
        txtAdmissionID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        txtPatientID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtPaid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDue = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Payment ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 134, 126, 31));

        txtPaymentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtPaymentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 134, 248, 31));

        txtAdmissionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdmissionIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtAdmissionID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 248, 29));

        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 126, 29));

        jLabel4.setText("Admission ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 126, 33));
        getContentPane().add(DateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 248, 40));

        txtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 248, 31));

        jLabel6.setText("Patient ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 126, 31));

        jLabel7.setText("Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 318, 126, 35));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 318, 248, 35));
        getContentPane().add(txtPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 359, 248, 34));

        jLabel8.setText("Paid");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 359, 126, 34));

        jLabel9.setText("Due");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 399, 126, 31));
        getContentPane().add(txtDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 399, 248, 31));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 153, 47));

        btnHome.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, 47));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Add Payment");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaymentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentIDActionPerformed

    }//GEN-LAST:event_txtPaymentIDActionPerformed

    private void txtAdmissionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdmissionIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdmissionIDActionPerformed

    private void txtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIDActionPerformed

    public boolean verifyText() {
//        if (txtID.getText().equals("") || txtName.getText().equals("") || txtBlood.getText().equals("") || txtAddress.getText().equals("") ||
//                DateChooser.getDate() == null || txtContact.getText().equals("") || txtEmContact.getText().equals("") || txtEmail.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "one or more empty field");
//            return false;
//        } /// choose a date higher than the current date
//        else if (DateChooser.getDate().compareTo(new Date()) > 0) {
//            JOptionPane.showMessageDialog(null, "invalid date");
//            return false;
//        } else {
            return true;
//        }
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            int PaymentID = Integer.valueOf(txtPaymentID.getText());
            int AdmissionID = Integer.valueOf(txtAdmissionID.getText());
            int PatientID = Integer.valueOf(txtPatientID.getText());
            int Total = Integer.valueOf(txtTotal.getText());
            int Paid = Integer.valueOf(txtPaid.getText());
            int Due = Integer.valueOf(txtDue.getText());

            SimpleDateFormat dateForm = new SimpleDateFormat("yyyy-MM-dd");
            String Date = dateForm.format(DateChooser.getDate());

            if(verifyText()) {
                Connection con = AllConnection.getConnection();
                PreparedStatement ps;

                try {
                    ps = con.prepareStatement("INSERT INTO `payment`(`PaymentID`, `Date`, `AdmissionID`, `PatientID`, `Total`, `Paid`, `Due`) "
                        + "VALUES (?,?,?,?,?,?,?)");

                    ps.setInt(1, PaymentID);
                    ps.setString(2, Date);
                    ps.setInt(3, AdmissionID);
                    ps.setInt(4, PatientID);
                    ps.setInt(5, Total);
                    ps.setInt(6, Paid);
                    ps.setInt(7, Due);

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(null, "New payment data added");
                    } else {
                        JOptionPane.showMessageDialog(null, "New payment data not added");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error in save");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        MainMenu form=new MainMenu();
        form.setVisible(true);
        dispose();
        form.setResizable(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAdmissionID;
    private javax.swing.JTextField txtDue;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPaymentID;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
